name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download ensoup
        run: wget https://github.com/enso-org/enso/releases/download/2025.2.4/enso-launcher-2025.2.4-linux-amd64.tar.gz

      - name: Untar ensoup
        run: tar fxvz enso-launcher-2025.2.4-linux-amd64.tar.gz

      - name: Install Enso
        run: ./enso/bin/ensoup install engine 2025.2.4 --hide-progress
        
      - name: List Enso compoonents
        run: ./enso/bin/ensoup list
        
      - name: Test all projects
        run: |
          for i in Dec*; do
            echo Running $i
            ./enso/bin/ensoup run $i
            echo Exit code: $?
          done

